# Generated by Django 4.2.7 on 2026-04-19 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('worker', 'Работник'), ('employer', 'Работодатель')], default='worker', max_length=10)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('auth_method', models.CharField(default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resume_photos/')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(choices=[('programmer', 'Программист'), ('teacher', 'Учитель'), ('doctor', 'Врач'), ('lawyer', 'Юрист'), ('accountant', 'Бухгалтер'), ('driver', 'Водитель'), ('engineer', 'Инженер'), ('designer', 'Дизайнер'), ('manager', 'Менеджер'), ('other', 'Другое')], max_length=50)),
                ('profession_other', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior'), ('lead', 'Lead'), ('no_category', 'Без категории'), ('category_2', '2-я категория'), ('category_1', '1-я категория'), ('highest', 'Высшая'), ('sheber', 'Шебер'), ('intern', 'Интерн'), ('resident', 'Резидент'), ('specialist', 'Специалист'), ('highest_med', 'Высшая категория'), ('rank_1', '1-й разряд'), ('rank_2', '2-й разряд'), ('rank_3', '3-й разряд'), ('rank_4', '4-й разряд'), ('rank_5', '5-й разряд'), ('rank_6', '6-й разряд'), ('beginner', 'Начинающий'), ('expert', 'Эксперт')], max_length=20)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент'), ('karaganda', 'Караганда'), ('aktobe', 'Актобе'), ('taraz', 'Тараз'), ('pavlodar', 'Павлодар'), ('ust_kamenogorsk', 'Усть-Каменогорск'), ('semey', 'Семей'), ('atyrau', 'Атырау'), ('kostanay', 'Костанай'), ('kyzylorda', 'Кызылорда'), ('uralsk', 'Уральск'), ('petropavlovsk', 'Петропавловск')], default='almaty', max_length=30)),
                ('has_bachelor', models.BooleanField(default=False)),
                ('bachelor_university', models.CharField(blank=True, max_length=255)),
                ('bachelor_years', models.CharField(blank=True, max_length=20)),
                ('has_master', models.BooleanField(default=False)),
                ('master_university', models.CharField(blank=True, max_length=255)),
                ('master_years', models.CharField(blank=True, max_length=20)),
                ('work_places', models.TextField(blank=True)),
                ('has_projects', models.BooleanField(default=False)),
                ('project_links', models.TextField(blank=True)),
                ('languages', models.JSONField(default=list)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.resume')),
            ],
            options={
                'unique_together': {('employer', 'resume')},
            },
        ),
    ]
